/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgentResponseAllOf1
 */
public class AgentResponseAllOf1Test {
    private final AgentResponseAllOf1 model = new AgentResponseAllOf1();

    /**
     * Model tests for AgentResponseAllOf1
     */
    @Test
    public void testAgentResponseAllOf1() {
        // TODO: test AgentResponseAllOf1
    }

    /**
     * Test the property 'lastModificationTimestamp'
     */
    @Test
    public void lastModificationTimestampTest() {
        // TODO: test lastModificationTimestamp
    }

}
