/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CallDetailAllOfE2eLatency;
import com.konfigthis.client.model.Utterance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CallDetailAllOf
 */
public class CallDetailAllOfTest {
    private final CallDetailAllOf model = new CallDetailAllOf();

    /**
     * Model tests for CallDetailAllOf
     */
    @Test
    public void testCallDetailAllOf() {
        // TODO: test CallDetailAllOf
    }

    /**
     * Test the property 'endTimestamp'
     */
    @Test
    public void endTimestampTest() {
        // TODO: test endTimestamp
    }

    /**
     * Test the property 'transcript'
     */
    @Test
    public void transcriptTest() {
        // TODO: test transcript
    }

    /**
     * Test the property 'transcriptObject'
     */
    @Test
    public void transcriptObjectTest() {
        // TODO: test transcriptObject
    }

    /**
     * Test the property 'recordingUrl'
     */
    @Test
    public void recordingUrlTest() {
        // TODO: test recordingUrl
    }

    /**
     * Test the property 'publicLogUrl'
     */
    @Test
    public void publicLogUrlTest() {
        // TODO: test publicLogUrl
    }

    /**
     * Test the property 'e2eLatency'
     */
    @Test
    public void e2eLatencyTest() {
        // TODO: test e2eLatency
    }

}
