/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CallDetailAllOfE2eLatency;
import com.konfigthis.client.model.Utterance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CallDetail
 */
public class CallDetailTest {
    private final CallDetail model = new CallDetail();

    /**
     * Model tests for CallDetail
     */
    @Test
    public void testCallDetail() {
        // TODO: test CallDetail
    }

    /**
     * Test the property 'callId'
     */
    @Test
    public void callIdTest() {
        // TODO: test callId
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    public void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'audioWebsocketProtocol'
     */
    @Test
    public void audioWebsocketProtocolTest() {
        // TODO: test audioWebsocketProtocol
    }

    /**
     * Test the property 'audioEncoding'
     */
    @Test
    public void audioEncodingTest() {
        // TODO: test audioEncoding
    }

    /**
     * Test the property 'sampleRate'
     */
    @Test
    public void sampleRateTest() {
        // TODO: test sampleRate
    }

    /**
     * Test the property 'callStatus'
     */
    @Test
    public void callStatusTest() {
        // TODO: test callStatus
    }

    /**
     * Test the property 'startTimestamp'
     */
    @Test
    public void startTimestampTest() {
        // TODO: test startTimestamp
    }

    /**
     * Test the property 'endCallAfterSilenceMs'
     */
    @Test
    public void endCallAfterSilenceMsTest() {
        // TODO: test endCallAfterSilenceMs
    }

    /**
     * Test the property 'fromNumber'
     */
    @Test
    public void fromNumberTest() {
        // TODO: test fromNumber
    }

    /**
     * Test the property 'toNumber'
     */
    @Test
    public void toNumberTest() {
        // TODO: test toNumber
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'retellLlmDynamicVariables'
     */
    @Test
    public void retellLlmDynamicVariablesTest() {
        // TODO: test retellLlmDynamicVariables
    }

    /**
     * Test the property 'endTimestamp'
     */
    @Test
    public void endTimestampTest() {
        // TODO: test endTimestamp
    }

    /**
     * Test the property 'transcript'
     */
    @Test
    public void transcriptTest() {
        // TODO: test transcript
    }

    /**
     * Test the property 'transcriptObject'
     */
    @Test
    public void transcriptObjectTest() {
        // TODO: test transcriptObject
    }

    /**
     * Test the property 'recordingUrl'
     */
    @Test
    public void recordingUrlTest() {
        // TODO: test recordingUrl
    }

    /**
     * Test the property 'publicLogUrl'
     */
    @Test
    public void publicLogUrlTest() {
        // TODO: test publicLogUrl
    }

    /**
     * Test the property 'e2eLatency'
     */
    @Test
    public void e2eLatencyTest() {
        // TODO: test e2eLatency
    }

}
