/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CallDetailAllOfE2eLatency
 */
public class CallDetailAllOfE2eLatencyTest {
    private final CallDetailAllOfE2eLatency model = new CallDetailAllOfE2eLatency();

    /**
     * Model tests for CallDetailAllOfE2eLatency
     */
    @Test
    public void testCallDetailAllOfE2eLatency() {
        // TODO: test CallDetailAllOfE2eLatency
    }

    /**
     * Test the property 'p50'
     */
    @Test
    public void p50Test() {
        // TODO: test p50
    }

    /**
     * Test the property 'p90'
     */
    @Test
    public void p90Test() {
        // TODO: test p90
    }

    /**
     * Test the property 'p95'
     */
    @Test
    public void p95Test() {
        // TODO: test p95
    }

    /**
     * Test the property 'p99'
     */
    @Test
    public void p99Test() {
        // TODO: test p99
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'num'
     */
    @Test
    public void numTest() {
        // TODO: test num
    }

}
