/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CallMakeConnectionRequestPhoneNumber;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CallMakeConnectionRequest
 */
public class CallMakeConnectionRequestTest {
    private final CallMakeConnectionRequest model = new CallMakeConnectionRequest();

    /**
     * Model tests for CallMakeConnectionRequest
     */
    @Test
    public void testCallMakeConnectionRequest() {
        // TODO: test CallMakeConnectionRequest
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'overrideAgentId'
     */
    @Test
    public void overrideAgentIdTest() {
        // TODO: test overrideAgentId
    }

    /**
     * Test the property 'retellLlmDynamicVariables'
     */
    @Test
    public void retellLlmDynamicVariablesTest() {
        // TODO: test retellLlmDynamicVariables
    }

}
