/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.State;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RetellLLMResponse
 */
public class RetellLLMResponseTest {
    private final RetellLLMResponse model = new RetellLLMResponse();

    /**
     * Model tests for RetellLLMResponse
     */
    @Test
    public void testRetellLLMResponse() {
        // TODO: test RetellLLMResponse
    }

    /**
     * Test the property 'llmId'
     */
    @Test
    public void llmIdTest() {
        // TODO: test llmId
    }

    /**
     * Test the property 'llmWebsocketUrl'
     */
    @Test
    public void llmWebsocketUrlTest() {
        // TODO: test llmWebsocketUrl
    }

    /**
     * Test the property 'generalPrompt'
     */
    @Test
    public void generalPromptTest() {
        // TODO: test generalPrompt
    }

    /**
     * Test the property 'generalTools'
     */
    @Test
    public void generalToolsTest() {
        // TODO: test generalTools
    }

    /**
     * Test the property 'states'
     */
    @Test
    public void statesTest() {
        // TODO: test states
    }

    /**
     * Test the property 'startingState'
     */
    @Test
    public void startingStateTest() {
        // TODO: test startingState
    }

    /**
     * Test the property 'beginMessage'
     */
    @Test
    public void beginMessageTest() {
        // TODO: test beginMessage
    }

    /**
     * Test the property 'lastModificationTimestamp'
     */
    @Test
    public void lastModificationTimestampTest() {
        // TODO: test lastModificationTimestamp
    }

}
