/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.PhoneNumberPurchaseNumberAndBindAgentRequest;
import com.konfigthis.client.model.PhoneNumberResponse;
import com.konfigthis.client.model.PhoneNumberUpdateRetellLlmRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PhoneNumberApi
 */
@Disabled
public class PhoneNumberApiTest {

    private static PhoneNumberApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PhoneNumberApi(apiClient);
    }

    /**
     * List all phone numbers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllNumbersTest() throws ApiException {
        List<PhoneNumberResponse> response = api.getAllNumbers()
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve details of a specific phone number
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        String phoneNumber = null;
        PhoneNumberResponse response = api.getDetails(phoneNumber)
                .execute();
        // TODO: test validations
    }

    /**
     * Buy a new phone number &amp; Bind an agent
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void purchaseNumberAndBindAgentTest() throws ApiException {
        String agentId = null;
        Integer areaCode = null;
        PhoneNumberResponse response = api.purchaseNumberAndBindAgent(agentId)
                .areaCode(areaCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete an existing phone number
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removePhoneNumberTest() throws ApiException {
        String phoneNumber = null;
        api.removePhoneNumber(phoneNumber)
                .execute();
        // TODO: test validations
    }

    /**
     * Update an existing Retell LLM
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRetellLlmTest() throws ApiException {
        String agentId = null;
        String phoneNumber = null;
        PhoneNumberResponse response = api.updateRetellLlm(agentId, phoneNumber)
                .execute();
        // TODO: test validations
    }

}
