/*
 * Retell SDK
 * API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@retellai.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.RetellLLMBase;
import com.konfigthis.client.model.RetellLLMResponse;
import com.konfigthis.client.model.State;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RetellApi
 */
@Disabled
public class RetellApiTest {

    private static RetellApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new RetellApi(apiClient);
    }

    /**
     * Delete an existing Retell LLM
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteLlmTest() throws ApiException {
        String llmId = null;
        api.deleteLlm(llmId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve details of a specific Retell LLM
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLlmDetailsTest() throws ApiException {
        String llmId = null;
        RetellLLMResponse response = api.getLlmDetails(llmId)
                .execute();
        // TODO: test validations
    }

    /**
     * Create a new Retell LLM
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void newLlmTest() throws ApiException {
        String generalPrompt = null;
        List<Object> generalTools = null;
        List<State> states = null;
        String startingState = null;
        String beginMessage = null;
        RetellLLMResponse response = api.newLlm()
                .generalPrompt(generalPrompt)
                .generalTools(generalTools)
                .states(states)
                .startingState(startingState)
                .beginMessage(beginMessage)
                .execute();
        // TODO: test validations
    }

    /**
     * Update an existing Retell LLM
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateLlmTest() throws ApiException {
        String llmId = null;
        String generalPrompt = null;
        List<Object> generalTools = null;
        List<State> states = null;
        String startingState = null;
        String beginMessage = null;
        RetellLLMResponse response = api.updateLlm(llmId)
                .generalPrompt(generalPrompt)
                .generalTools(generalTools)
                .states(states)
                .startingState(startingState)
                .beginMessage(beginMessage)
                .execute();
        // TODO: test validations
    }

}
